version: "3"
services:
  db:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    restart: always
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8787:8787"
    depends_on:
      - db
    restart: always
